### ISSUE TITLE
Screen-Scraping RTT Will Break When New Site Design Released

### ISSUE THREAD

**Issue by IgnoredAmbience** [mattallinson/NuclearTrains#4]
In [an exchange with the RTT creator](https://twitter.com/swlines/status/882568690469941249), he noted that the site will likely break when the RTT site is redesigned in the (near?) future.

Have you considered using the [API](https://api.rtt.io/)?

**Comment by keirwl** [comment]
Hi,

We have wanted to use the API from the beginning, but an email sent to api@realtimetrains.co.uk at the time bounced. This, combined with the site being "© 2011-2013" made us think it was no longer maintained.
Thank you for the API link, I will register now.

**Comment by IgnoredAmbience** [comment]
It took me a while to get a response from the api@ email address a couple of months ago, only from that response did I find the API registration page. hohum...

**Comment by keirwl** [comment]
Fixed by #5

**Comment by keirwl** [comment]
Fixed by #5
